[package]
name = "prime"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
argh = "0.1"

[dependencies.num-bigint]
version = "0.3"
features = ["rand"]
